### ISSUE TITLE
Makefile with white spaces

### ISSUE THREAD

**Issue by cadicallegari** [fniessen/orgmk#11]
Using GNU Make I received the follow message:

> Makefile:42: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

It shouldn't be tabs? or I'm doing something wrong?

**Comment by fniessen** [comment]
Hello. Of course, it should. TABs have been converted to spaces because of my Emacs config. Added a local var in README.org to avoid that in the future.

Thanks.
