### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by 46do14** [fniessen/orgmk#35]
file is missing: orgmk-update-src 

make: *** [Makefile:62: install] Error 1

**Comment by fniessen** [comment]
Dear @46do14 , could you confirm it's now OK?

I can't find that file on my system either, it seems to be something that has been obsoleted over time... So I got rid of those references...

**Comment by 46do14** [comment]
Dear Fabrice, thank you so much for fixing it. orgmk is now successfully installed :)

**Comment by fniessen** [comment]
My pleasure!
