### ISSUE TITLE
org file with R block and ":comments yes" does not tangle

### ISSUE THREAD

**Issue by rkrug** [fniessen/orgmk#7]
The following org file does not tangle using org-tangle:

test.org:
```
#+PROPERTY: header-args :comments yes

* Data
** CACHE
#+begin_src R  :tangle test.sh
cat(13)
#+end_src
```

```
05:00:02 ~/tmp$ org-tangle test.org
This is org-tangle, version: 20150710.1537.
Launching /usr/local/bin/emacs...
Emacs 25.0.50.1 (darwin)
Loading /Users/rainerkrug/.emacs.d/orgmk/site-lisp/orgmk.el...
Current value of ‘shell-file-name’: /usr/local/bin/bash
... changed to: bash
Org mode version 8.2.10 (org @ /usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/org/)
LaTeX command: ("latexmk -CF -pdf %f && latexmk -c")
Loading /Users/rainerkrug/.emacs.d/orgmk/lisp/org-latex-classes.el (source)...
Convergence after 1 iterations
Tangled 1 code block from test.orgmk
05:00:14 ~/tmp$
```

Tangling the same file without comments works.

**Comment by fniessen** [comment]
So you mean that Org mode telling "Tangled 1 code block from test.orgmk" is somehow lying?

Can you also test it with other Emacs versions than Emacs 25.0.50.1?

**Comment by rkrug** [comment]
Sorry - wrong output. Here is the correct one:

```
05:31:37 ~/tmp$ org-tangle test.org
This is org-tangle, version: 20150710.1537.
Launching /usr/local/bin/emacs...
Emacs 25.0.50.1 (darwin)
Loading /Users/rainerkrug/.emacs.d/orgmk/site-lisp/orgmk.el...
Current value of ‘shell-file-name’: /usr/local/bin/bash
... changed to: bash
Org mode version 8.2.10 (org @ /usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/org/)
LaTeX command: ("latexmk -CF -pdf %f && latexmk -c")
Loading /Users/rainerkrug/.emacs.d/orgmk/lisp/org-latex-classes.el (source)...
Convergence after 1 iterations
No comment syntax is defined.  Use:
No comment syntax defined
org-tangle: File wasn't tangled
05:32:30 ~/tmp$
```

and here for 24.5.1:

```
05:33:46 ~/tmp$ org-tangle test.org
This is org-tangle, version: 20150710.1537.
Launching /usr/local/bin/emacs...
Emacs 24.5.1 (darwin)
Loading /Users/rainerkrug/.emacs.d/orgmk/site-lisp/orgmk.el...
Current value of `shell-file-name': /usr/local/bin/bash
... changed to: bash
Org mode version 8.2.10 (org @ /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.10/share/emacs/24.5/lisp/org/)
LaTeX command: ("latexmk -CF -pdf %f && latexmk -c")
Loading /Users/rainerkrug/.emacs.d/orgmk/lisp/org-latex-classes.el (source)...
Convergence after 1 iterations
Saving file /Users/rainerkrug/tmp/test.orgmk...
Wrote /Users/rainerkrug/tmp/test.orgmk
(No changes need to be saved)
No comment syntax is defined.  Use:
No comment syntax defined
org-tangle: File wasn't tangled
05:33:52 ~/tmp$
```

**Comment by fniessen** [comment]
So, it seems the error "No comment syntax is defined" really means something in this case. It is because of the language you use?  You should apparently define "comment-start" or such as a local var in your Org file, right?

What does it do with another language for your code block?

**Comment by rkrug** [comment]
Sorry - I thought I posted it already. 
The language does not change anything - same result when using sh.

**Comment by rkrug** [comment]
Any news on this issue? I would very much like to use org-tangle in a makefile and I am tangling with comments.

**Comment by fniessen** [comment]
Nope. And, unluckily, I won't investigate it in the coming weeks (or months)... I've been busy searching (by force) for a new job these last months, and am beginning next Monday with a new one.

I know that I have lots of open issues, in many different projects, and I'm sorry it's like that, but the only way to make these progress will be to investigate by yourself why there's a problem there.

Thanks!

**Comment by rkrug** [comment]
That's fine - I'll see if I find time. 

Good luck with your new job!

**Comment by ewa** [comment]
So, I have essentially the same problem, and an (ugly) solution.  I'm tangling protocol buffers (protobuf-mode files) from org-babel, and it barfs if
(a) :comments yes is set and
(b) protobuf-mode is not already loaded.

My normal .emacs requires protobuf-mode, so it's all good.  But, orgmk from the command line does not (understandably) and so it fails. 

I feel like the *real* solution is to fix org-babel mode to do a smart "search for appropriate mode and load it" when a code block is encountered, but that's more time/work/smarts than I have to spare.

Instead, I just hacked up orgmk to always load protobuf-mode, and it solves my problem:  https://github.com/ewa/orgmk

**Comment by fniessen** [comment]
Thanks for adding data points to this story!

IIUC, isn't the following the (or a) solution: add your custom code (loading protobuf-mode) in one .el file in the lisp directory.  Those files are read by default...

**Comment by ewa** [comment]
Fniessen:  Yup, that's a solution.  I only ran into this issue when I started sharing this code with other developers, and I realized that while it was working on *my* emacs setup, it wasn't working on *theirs*.  I was looking for a solution that didn't require other developers (who aren't all regular emacs users) to have to do any special configuration.   In fact, half of why I started using orgmk for this was so they could just edit the files in `vi` and run a command-line utility to tangle them up.

**Comment by fniessen** [comment]
OK. Glad to know everything was built-in to work around those peculiar situations.

About vi users or users of Make, yes, for sure, I've done this so that more people can use Org files (and enjoy it!).

**Comment by rkrug** [comment]
The only not so nice aspect is that the lisp directory is in the installation directory of orgmk. It would be nicer if one could put this file in a different directory which could be specified by a command line argument.

**Comment by fniessen** [comment]
Hello Rainer. Do you want to provide a patch?
