### ISSUE TITLE
Syntax highlighting in HTML export

### ISSUE THREAD

**Issue by ewa** [fniessen/orgmk#8]
Hi!  Another issue / question:

I notice that when I export to HTML from within my interactive emacs sessions, my source code blocks get syntax highlighted, but when I run `org2html` the same file, they don't.  Do you know of a setting for that?

Thanks,
Eric

**Comment by fniessen** [comment]
That has to do with htmlize not being loaded/run, something around that particular package.  Please note that you may have to use the version provided in org/contrib.
